config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  resources :departments
  resources :students

  root 'welcome#index'
  resources :instructors do
  resources :departments 
  resources :students

end
end

app/models/department.rb
class Department < ActiveRecord::Base

belongs_to :instructors
belongs_to :students
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base

# valdiates :departments, limit: 3
has_many :departments
has_many :students, through: :departments, dependent: :destroy

end

app/models/student.rb
class Student < ActiveRecord::Base

has_many :departments
has_many :instructors, through: :departments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end
  def show
    @department = Department.find(params[:id])
    @departments = Department.all

  end
  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path, notice: "Department Successfully Created"
    else
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    redirect_to departments_path
  end


  private
    def department_params
      params.require(:department).permit(:subject, :student_id, :instructor_id)
    end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  def index
    @instructors = Instructor.all
    @departments = Department.all
  end

  def new
    @instructor = Instructor.new
    @department = Department.new
  end
  def show
    @instructor = Instructor.find(params[:id])
    @instructors = Instructor.all

  end
  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to instructors_path, notice: "Instructor Successfully Created"
    else
      render :new
    end
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update(instructor_params)
      redirect_to instructors_path
    else
      render :edit
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to instructors_path
  end


  private
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end
  def show
    @student = Student.find(params[:id])
    @students = Student.all

  end
  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: "Student Successfully Created"
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end


  private
    def student_params
      params.require(:student).permit(:first_name, :last_name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/departments/edit.html.erb
<%= form_for @department do |f| %>
<p>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/departments/index.html.erb
<h1>Department:</h1>

<%= link_to "Create Departments", new_department_path %>
<table>
  <thead>
    <tr>
      <th>Subject</th>
    </tr>
    <thead>
      <tbody>
<%= @departments.each do |department| %>
<tr>
<td><%= link_to department.subject, department_path(department) %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/departments/new.html.erb
<%= form_for @department, url: departments_path do |f| %>
<p>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/departments/show.html.erb
<%= @department.subject %>

<%= link_to "Edit", edit_department_path %>

<%= link_to 'Delete', department_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/instructors/edit.html.erb
<%= form_for @instructor do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/instructors/index.html.erb
<h1>Instructors:</h1>

<%= link_to "Create Instructors", new_instructor_path %>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
    </tr>
    <thead>
      <tbody>
<%= @instructors.each do |instructor| %>
<tr>
<td><%= link_to instructor.first_name, instructor_path(instructor) %></td>
<td><%= instructor.last_name %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/instructors/new.html.erb
<%= form_for @instructor, url: instructors_path do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/instructors/show.html.erb
<%= @instructor.first_name %>

<%= link_to "Edit", edit_instructor_path %>

<%= link_to 'Delete', instructor_path, method: :delete, data: { confirm: 'Are you sure?' } %>

<table>
  <thead>
    <tr>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= form_for [@department, @instructor] do |f| %>

      <td> <%= collection_select( :department, :department_id, Department.all, :id, :subject, {}, ) %></td>
      <td><%= f.submit %></td>

      <% end %>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assessment3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/students/index.html.erb
<h1>Students:</h1>

<%= link_to "Create Students", new_student_path %>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
    </tr>
    <thead>
      <tbody>
<%= @students.each do |student| %>
<tr>
<td><%= link_to student.first_name, student_path(student) %></td>
<td><%= student.last_name %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/students/new.html.erb
<%= form_for @student, url: students_path do |f| %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/students/show.html.erb
<%= @student.first_name %>

<%= link_to "Edit", edit_student_path %>

<%= link_to 'Delete', student_path, method: :delete, data: { confirm: 'Are you sure?' } %>

<table>
  <thead>
    <tr>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= form_for [@department, @student] do |f| %>

      <td> <%= collection_select( :department, :department_id, Department.all, :id, :subject, {}, ) %></td>
    <td>  <%= f.submit %></td>

      <% end %>
    </tr>
  </tbody>
</table>

app/views/welcome/index.html.erb
<p>
  <%= link_to "Instructors", instructors_path %>
</p>
<p>
  <%= link_to "Students", students_path %>
</p>
<p>
  <%= link_to "Departments", departments_path %>
</p>